#include "lazycmake/cmake_gen/cmake_printer.hpp"

#include <sstream>
#include <string_view>

namespace lazycmake::cmake_gen {

CMakePrinter::CMakePrinter(Options opts)
    : options_(std::move(opts)) {}

void CMakePrinter::setOptions(const Options& opts) {
    options_ = opts;
}

std::string CMakePrinter::print(const CMakeFile& cmakeFile) const {
    std::ostringstream oss;

    // Optional header comment — identifies the file as auto-generated.
    // This is the "nothing is hidden" principle (§1): every generated file
    // clearly states it was generated by LazyCMake so a hand-editor knows
    // what they're looking at. The hand-edit warning (§10.4) builds on top
    // of this by also hashing the file; the comment is a human-friendly cue.
    if (options_.includeHeader) {
        oss << "# Generated by LazyCMake\n";
        oss << "# https://github.com/anomalyco/lazycmake\n";
        if (options_.includeHandEditWarning) {
            oss << "#\n";
            oss << "# This file was generated by LazyCMake from your project model.\n";
            oss << "# Edits will be detected and NOT silently overwritten — see\n";
            oss << "# the hand-edit detection docs (§10.4 in DESIGN.md).\n";
            oss << "# To stop tracking this file within LazyCMake, use the\n";
            oss << "# 'Keep Mine' option when the edit is detected.\n";
        }
        oss << "\n";
    }

    // Render each element in order.
    for (const auto& element : cmakeFile.elements()) {
        switch (element.type) {
            case CMakeFile::ElementType::Statement:
                oss << printStatement(element.statement);
                if (!element.statement.noTrailingNewline) {
                    oss << '\n';
                }
                break;

            case CMakeFile::ElementType::Comment:
                // Render as "# <text>" — a comment line.
                // Multi-line comments are split on \n within the string.
                {
                    std::istringstream commentStream(element.comment);
                    std::string line;
                    while (std::getline(commentStream, line)) {
                        oss << "# " << line << '\n';
                    }
                }
                break;

            case CMakeFile::ElementType::BlankLine:
                oss << '\n';
                break;
        }
    }

    return oss.str();
}

std::string CMakePrinter::printStatement(const CMakeStatement& stmt) const {
    std::ostringstream oss;

    // Render the comment if present (before the statement).
    if (!stmt.comment.empty()) {
        std::istringstream commentStream(stmt.comment);
        std::string line;
        while (std::getline(commentStream, line)) {
            oss << "# " << line << '\n';
        }
    }

    // Render the command name.
    oss << stmt.command << '(';

    // Render arguments.
    for (size_t i = 0; i < stmt.arguments.size(); ++i) {
        if (i > 0) {
            oss << ' ';
        }
        oss << renderArg(stmt.arguments[i]);
    }

    oss << ')';

    return oss.str();
}

std::string CMakePrinter::renderArg(const std::string& arg) const {
    // If the statement has quoteArgs enabled, always quote.
    // Otherwise, quote only if the argument contains characters that
    // CMake would interpret specially (spaces, parentheses, #, etc.).
    if (options_.maxLineLength > 0 && arg.length() > static_cast<size_t>(options_.maxLineLength)) {
        // Long arguments are kept as-is; CMake handles long lines fine.
        // A future enhancement could split across multiple lines.
    }

    // If the argument is empty, render as empty string.
    if (arg.empty()) {
        return "\"\"";
    }

    return arg;
}

bool CMakePrinter::needsQuoting(const std::string& arg) const {
    // CMake identifiers cannot contain spaces, parentheses, quotes, #
    // at the start, or be empty (handled above). If the argument has any
    // of these, it needs quoting.
    if (arg.empty()) return true;

    for (char c : arg) {
        if (c == ' ' || c == '\t' || c == '(' || c == ')' ||
            c == '#' || c == '"' || c == '\\') {
            return true;
        }
    }
    return false;
}

} // namespace lazycmake::cmake_gen
