#pragma once

// ==========================================================================
// CMakePrinter — renders a CMakeFile AST into formatted CMake text (§10.2)
//
// This is the second half of the AST split: after the generator builds a
// CMakeFile from the Project model, the printer turns it into the actual
// CMakeLists.txt text. Separating these concerns means:
//   - Plugin AST hooks never need to worry about formatting.
//   - The printer can be tested independently with hand-built AST fixtures.
//   - Formatting style changes (indentation, blank-line grouping, comment
//     style) are localized to one file.
//
// The printer handles:
//   - Statement indentation (none at top level; 4-space inside blocks
//     like if/endif or foreach/endforeach, though we don't generate those
//     in Phase 2 — this is a forward-looking API design).
//   - Argument quoting (paths with spaces, CACHE variable strings).
//   - Comments and blank lines between statements.
//   - File-header boilerplate (generated-by notice).
// ==========================================================================

#include <string>

#include "lazycmake/cmake_gen/cmake_file.hpp"

namespace lazycmake::cmake_gen {

class CMakePrinter {
public:
    // Options to control printer behavior.
    struct Options {
        // Whether to include the "Generated by LazyCMake" header comment.
        bool includeHeader = true;

        // Whether to include the hand-edit warning comment.
        bool includeHandEditWarning = true;

        // Indentation string (4 spaces by default).
        std::string indent = "    ";

        // Max line length hint (0 = no limit). The printer does NOT
        // forcibly wrap lines (CMake syntax is flexible); this is a
        // formatting guideline for things like long target_link_libraries
        // calls where we may want to break arguments across lines.
        int maxLineLength = 0;
    };

    CMakePrinter() : CMakePrinter(Options{}) {}
    explicit CMakePrinter(Options opts);

    // Render the entire CMakeFile to a string.
    // This is the main entry point: call this with the AST produced by
    // ModernCMakeGenerator and write the result to a CMakeLists.txt.
    [[nodiscard]] std::string print(const CMakeFile& cmakeFile) const;

    // Render a single statement to a string (useful for testing).
    [[nodiscard]] std::string printStatement(const CMakeStatement& stmt) const;

    // Update printer options.
    void setOptions(const Options& opts);

private:
    Options options_;

    // Render an individual argument, quoting if needed.
    [[nodiscard]] std::string renderArg(const std::string& arg) const;

    // Check if a string needs quoting (contains spaces, special chars).
    [[nodiscard]] bool needsQuoting(const std::string& arg) const;
};

} // namespace lazycmake::cmake_gen
